spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    generate-ddl: true
    show-sql: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  h2:
    console:
      enabled: true